CREATE TABLE offline_teacher_application (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    teacher_name VARCHAR(64) NOT NULL,
    id_card_ciphertext VARBINARY(512) NOT NULL,
    id_card_iv BINARY(12) NOT NULL,
    id_card_hmac BINARY(32) NOT NULL UNIQUE,
    id_card_masked VARCHAR(32) NOT NULL,
    gender VARCHAR(16) NOT NULL,
    education_level VARCHAR(32) NOT NULL,
    education_background VARCHAR(1000) NOT NULL,
    institution VARCHAR(200),
    province VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    district VARCHAR(100),
    bio VARCHAR(2000) NOT NULL,
    teaching_content VARCHAR(2000) NOT NULL,
    teaching_tags CLOB NOT NULL,
    availability VARCHAR(1000),
    hourly_rate DECIMAL(10,2) NOT NULL,
    price_description VARCHAR(500),
    contact_wechat VARCHAR(100),
    contact_qq VARCHAR(32),
    contact_email VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    rejection_reason VARCHAR(1000),
    submitted_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    reviewed_by BIGINT,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_test_teacher_application_user
        FOREIGN KEY (user_id) REFERENCES `user` (id),
    CONSTRAINT fk_test_teacher_application_reviewer
        FOREIGN KEY (reviewed_by) REFERENCES `user` (id)
);

CREATE TABLE offline_teacher_profile (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    source_application_id BIGINT NOT NULL UNIQUE,
    teacher_name VARCHAR(64) NOT NULL,
    gender VARCHAR(16) NOT NULL,
    education_level VARCHAR(32) NOT NULL,
    education_background VARCHAR(1000) NOT NULL,
    institution VARCHAR(200),
    province VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    district VARCHAR(100),
    bio VARCHAR(2000) NOT NULL,
    teaching_content VARCHAR(2000) NOT NULL,
    teaching_tags CLOB NOT NULL,
    availability VARCHAR(1000),
    hourly_rate DECIMAL(10,2) NOT NULL,
    price_description VARCHAR(500),
    contact_wechat VARCHAR(100),
    contact_qq VARCHAR(32),
    contact_email VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    suspended_reason VARCHAR(1000),
    approved_at TIMESTAMP NOT NULL,
    approved_by BIGINT NOT NULL,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_test_teacher_profile_user
        FOREIGN KEY (user_id) REFERENCES `user` (id),
    CONSTRAINT fk_test_teacher_profile_application
        FOREIGN KEY (source_application_id) REFERENCES offline_teacher_application (id),
    CONSTRAINT fk_test_teacher_profile_approver
        FOREIGN KEY (approved_by) REFERENCES `user` (id)
);
